version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website_3.0
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: contact_backend
    ports:
      - "3001:3001"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
