services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - CHICKID_INSECT=false
    restart: unless-stopped
    networks:
      - website_net


networks:
  website_net:
    driver: bridge
